### ISSUE TITLE
Why the regression in versioning?

### ISSUE THREAD

**Issue by alerque** [theacodes/cmarkgfm#51]
Calendar versioning is less usable and less informative for downstream users, especially packagers (Arch Linux packager here). Additionally now there is a disparity between Git tags and the internal version marker and even the PyPi release. Can we please just tag the semver as well? Thanks for considering.

**Comment by alerque** [comment]
This also is going to trip up projects that need to call out dependencies on this project.

**Comment by theacodes** [comment]
Since this is a thin wrapper over the underlying C library, there isn't a lot of information semver could contain for us. We won't be switching back from calver.

**Comment by alerque** [comment]
> there isn't a lot of information semver could contain for us

Sure there is, at a minimum it can pass on the major/minor/patch semver semantics from the underlying C library. That way Python dependencies can be sanely versioned with the same logic. It doesn't have to be same numbers, but a major version in the library should turn up a major version of the wrapper, etc. Additionally any future major changes to the way the wrapper version works would also trigger similar major bumps. The same on down the line.

**Comment by alerque** [comment]
Also don't break the existing PyPi release, it is already in distributions downstream. Tag something else if you must but don't drop v0.8.0.

**Comment by theacodes** [comment]
The scheme you described sounds great in theory, but doesn't work in practice. They'll drift out of coherence pretty quickly, and then the version number for the wrapper will no longer convey any useful information about the underlying library. In fact, it'll be confusing since it will *look* like it might be the version of the underlying library, but it isn't.

The underlying library, and therefore this wrapper, are pretty stable. The underlying library hasn't made any breaking API changes during the entire existence of this wrapper.

> Also don't break the existing PyPi release, it is already in distributions downstream. Tag something else if you must but don't drop v0.8.0.

I won't yank the release from PyPI, I'm not a monster.

Also, to be *totally* transparent: the primary purpose of this library is to support PyPA/Warehouse and PyPA/readme_renderer. I have very limited ability to support other projects.
